export const CATEGORIES = [
  { key: "airport", label: "Airport", icon: "✈️" },
  { key: "weapon_store", label: "Ammunation/Weapon Store", icon: "🔫" },
  { key: "bank", label: "Bank", icon: "🏦" },
  { key: "bridge", label: "Bridge", icon: "🌉" },
  { key: "bus_station", label: "Bus Station", icon: "🚌" },
  { key: "bar", label: "Bar", icon: "🍻" },
  { key: "barber", label: "Barber", icon: "✂️" },
  { key: "black_market", label: "Black Market", icon: "🤫" },
  { key: "boat_dealer", label: "Boat Dealer", icon: "🛥️" },
  { key: "business", label: "Business", icon: "🏢" },
  { key: "car_dealer", label: "Car Dealership", icon: "🚗" },
  { key: "car_wash", label: "Car Wash", icon: "🧼" },
  { key: "casino", label: "Casino", icon: "🎰" },
  { key: "church", label: "Church", icon: "⛪" },
  { key: "city_hall", label: "City Hall", icon: "🏛️" },
  { key: "clothing_store", label: "Clothing Store", icon: "👕" },
  { key: "club", label: "Club", icon: "🎧" },
  { key: "convenience_store", label: "Convenience Store", icon: "🛒" },
  { key: "digitalden", label: "DigitalDen", icon: "💻" },
  { key: "drug_lab", label: "Drug Lab", icon: "🧪" },
  { key: "fire", label: "Fire Station", icon: "🚒" },
  { key: "gas_station", label: "Gas Station", icon: "⛽" },
  { key: "gym", label: "Gym", icon: "💪" },
  { key: "gang_mc", label: "Gang/MC", icon: "🏍️" },
  { key: "heist_robbery", label: "Heist/Robbery", icon: "💰" },
  { key: "hospital", label: "Hospital", icon: "🏥" },
  { key: "hotel", label: "Hotel", icon: "🏨" },
  { key: "hunting", label: "Hunting", icon: "🏹" },
  { key: "hunting_store", label: "Hunting Store", icon: "🦌" },
  { key: "island", label: "Island", icon: "🏝️" },
  { key: "laundromat", label: "Laundromat", icon: "🧺" },
  { key: "mall", label: "Mall", icon: "🏬" },
  { key: "map", label: "Map", icon: "🗺️" },
  { key: "mechanic", label: "Mechanic Shop", icon: "🛠️" },
  { key: "park", label: "Park", icon: "🌳" },
  { key: "pawn_shop", label: "Pawn Shop", icon: "🏪" },
  { key: "pet_store", label: "Pet Store", icon: "🐾" },
  { key: "police", label: "Police Station", icon: "🚓" },
  { key: "prison", label: "Prison", icon: "🔒" },
  { key: "property", label: "Property", icon: "🏠" },
  { key: "restaurant", label: "Restaurant", icon: "🍽️" },
  { key: "sports", label: "Sports", icon: "🏟️" },
  { key: "store", label: "Store", icon: "🛍️" },
  { key: "storage_center", label: "Storage Center", icon: "📦" },
  { key: "tattoo", label: "Tattoo Shop", icon: "🖋️" },
  { key: "theater", label: "Theater", icon: "🎭" },
] as const;

export type CategoryKey = (typeof CATEGORIES)[number]["key"];
